# Generated by Django 2.2.4 on 2019-09-08 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aidooit_people', '0007_auto_20190908_0258'),
        ('aidooit_login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='person_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='aidooit_people.Person'),
            preserve_default=False,
        ),
    ]
