# Generated by Django 2.2.4 on 2019-09-08 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aidooit_login', '0002_login_person_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='person_id',
            new_name='person',
        ),
    ]
