# Generated by Django 2.2.4 on 2019-09-08 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aidooit_access_point', '0002_aidooitaccesspoint_address'),
        ('aidooit_login', '0003_auto_20190908_0317'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='aap',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='aidooit_access_point.AidooitAccessPoint'),
            preserve_default=False,
        ),
    ]
