# Generated by Django 2.2.4 on 2019-09-09 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aidooit_login', '0004_login_aap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='aap',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aidooit_access_point.AidooitAccessPoint', verbose_name='AAP'),
        ),
    ]
