version: '3.7'

services:
  db:
    image: postgres:10.1-alpine
    container_name: db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  web:
    build: .
    container_name: web
    #command: django-admin startproject aidooit_camera_system .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db

volumes:
  postgres_data:
