# Generated by Django 2.2.4 on 2019-09-08 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidooit_access_point', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aidooitaccesspoint',
            name='address',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
    ]
