# Generated by Django 2.2.3 on 2019-07-11 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aidooit_people', '0004_personhistory_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personhistory',
            options={'verbose_name_plural': 'Person Historical'},
        ),
    ]
