# Generated by Django 2.2.4 on 2019-09-09 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aidooit_people', '0007_auto_20190908_0258'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='access_key',
            field=models.CharField(default='as123456', max_length=10),
        ),
    ]
